---
- name: Cloning or updating the repository ...
  git:
    repo: https://github.com/neilluna/bash-environment.git
    dest: "{{ bash_environment.dir }}"
    version: "{{ bash_environment.version }}"
  register: bash_environment_git_status

- name: Installing or updating ...
  when: bash_environment_git_status.before != bash_environment_git_status.after
  block:

  - name: Setting the local core filemode ...
    git_config:
      name: core.filemode
      repo: "{{ bash_environment.dir }}"
      scope: local
      value: "false"

  - name: Forcing an install ...
    set_fact:
      bash_environment.managed_externally: true

  # End of block: name: Installing ...
