---
- name: Checking if ~/.bashrc.d/pyenv-vars.sh exists and is a file ...
  stat:
    path: ~/.bashrc.d/pyenv-vars.sh
  register: stat_pyenv_vars_sh

- when: not (stat_pyenv_vars_sh.stat.exists and stat_pyenv_vars_sh.stat.isreg)
  block:

  - import_tasks: tasks/install_or_update.yml
    vars:
      action: install

  - name: Adding {{ role_name }} to ~/.dev-sys/installation-manifest.txt ...
    lineinfile:
      path: ~/.dev-sys/installation-manifest.txt
      line: '{{ role_name }}'

  # End of block: when: not (stat_pyenv_vars_sh.stat.exists and stat_pyenv_vars_sh.stat.isreg)

- when: stat_pyenv_vars_sh.stat.exists and stat_pyenv_vars_sh.stat.isreg
  block:

  - name: Checking if {{ role_name }} is in ~/.dev-sys/installation-manifest.txt ...
    command: grep -xq {{ role_name }} ~/.dev-sys/installation-manifest.txt
    register: grep_manifest_for_pyenv_environment
    changed_when: false
    failed_when: false

  - when: grep_manifest_for_pyenv_environment.rc == 0
    import_tasks: tasks/install_or_update.yml
    vars:
      action: update

  # End of block: when: stat_pyenv_vars_sh.stat.exists and stat_pyenv_vars_sh.stat.isreg
