---
- name: Installing the Bash startup script ...
  copy:
    src: .bashrc.d/pyenv-vars.sh
    dest: '{{ ansible_user_dir }}/.bashrc.d/pyenv-vars.sh'
    mode: u+x

- name: Marking the role as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated }} + [ '{{ role_name }}' ]"
