---
# If ini_file (in set-profile.yml) creates a file, then the file will have a
# blank line as the first line in the file. Wierd. The following task creates
# the configuartion files, if they do not exist, so that ini_file will not
# have to do so.
- name: Installing the config files ...
  copy:
    dest: ~/.aws/
    src: .aws/
    force: no

- name: Setting profiles ...
  include_tasks: set-profile.yml
  loop: "{{ aws_configuration.profiles }}"
  loop_control:
    loop_var: profile
