---
- name: Setting profile {{ profile.name }} region ...
  ini_file:
    path: ~/.aws/config
    section: "profile {{ profile.name }}"
    option: region
    value: "{{ profile.region }}"
    mode: u+rw-x,go-rxw

- name: Setting profile {{ profile.name }} output ...
  ini_file:
    path: ~/.aws/config
    section: "profile {{ profile.name }}"
    option: output
    value: "{{ profile.output }}"
    mode: u+rw-x,go-rxw

- name: Setting profile {{ profile.name }} aws_access_key_id ...
  ini_file:
    path: ~/.aws/credentials
    section: "{{ profile.name }}"
    option: aws_access_key_id
    value: "{{ profile.aws_access_key_id }}"
    mode: u+rw-x,go-rxw

- name: Setting profile {{ profile.name }} aws_secret_access_key ...
  ini_file:
    path: ~/.aws/credentials
    section: "{{ profile.name }}"
    option: aws_secret_access_key
    value: "{{ profile.aws_secret_access_key }}"
    mode: u+rw-x,go-rxw
