---
- name: Running apt safe upgrade ...
  apt:
    force_apt_get: yes
    upgrade: safe
  become: yes

- name: Marking the role as executed ...
  set_fact:
    roles_already_executed: "{{ roles_already_executed }} + [ '{{ role_name }}' ]"
