---
- name: Installing ...
  copy:
    src: bin/dev-sys.sh
    dest: '{{ ansible_env.HOME }}/bin/dev-sys.sh'
    mode: u+x

- name: Marking the role as executed ...
  set_fact:
    roles_already_executed: "{{ roles_already_executed }} + [ '{{ role_name }}' ]"
