---
- name: Installing ...
  copy:
    src: bin/dev-sys.sh
    dest: '{{ ansible_user_dir }}/bin/dev-sys.sh'
    mode: u+x

- name: Marking the role as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated }} + [ '{{ role_name }}' ]"
