---
- name: Installing ...
  pip:
    name: pipenv
    state: latest
  become: yes

- name: Installing the Bash startup scripts ...
  shell: '{{ ansible_env.HOME }}/provisioning/bash-environment/install.sh --pipenv-venv-in-project'
  when: bash_environment_status.before != bash_environment_status.after
