---
- name: If managed by this role (not externally) ...
  when: bash_environment_managed_externally == false
  include_tasks: tasks/managed_here.yml

- name: If managed externally (not by this role) ...
  when: bash_environment_managed_externally == true
  include_tasks: tasks/managed_externally.yml

- name: Installing ...
  when: run_install == true
  block:

  - name: Making install.sh executable ...
    file:
      path: '{{ bash_environment_dir }}/install.sh'
      state: file
      mode: u+x

  - name: Installing the Bash startup scripts ...
    shell: '{{ bash_environment_dir }}/install.sh'

  # End of block: name: Installing ...

- name: Marking the role as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated }} + [ '{{ role_name }}' ]"
