---
- name: Cloning or updating the repository ...
  git:
    repo: https://github.com/neilluna/bash-environment.git
    dest: '{{ bash_environment_dir }}'
    version: '{{ bash_environment_version }}'
  register: bash_environment_git_status

- name: Checking if the repository changed ...
  set_fact:
    run_install: '{{ bash_environment_git_status.before != bash_environment_git_status.after }}'

- name: Setting the local core filemode ...
  when: run_install == true
  git_config:
    name: core.filemode
    repo: '{{ bash_environment_dir }}'
    scope: local
    value: 'false'
