---
- name: Cloning or updating the repository ...
  git:
    repo: https://github.com/neilluna/bash-environment.git
    dest: "{{ bash_environment.dir }}"
    version: "{{ bash_environment.version }}"
  register: bash_environment_git_status

- name: Checking if the repository changed ...
  set_fact:
    run_install: '{{ bash_environment_git_status.before != bash_environment_git_status.after }}'

- name: Installing or updating ...
  when: run_install == true
  block:

  - name: Setting the local core filemode ...
    git_config:
      name: core.filemode
      repo: "{{ bash_environment.dir }}"
      scope: local
      value: "false"

  # End of block: name: Installing or updating ...
