---
- name: Installing the prerequisites ...
  apt:
    name: libnss3-tools
    force_apt_get: yes
    state: latest
  become: yes

- name: Installing ...
  get_url:
    url: https://github.com/FiloSottile/mkcert/releases/download/v{{ mkcert_version }}/mkcert-v{{ mkcert_version }}-linux-amd64
    dest: /usr/local/bin/mkcert
    group: root
    mode: u+rwx,go+rx-w
    owner: root
  become: yes

- name: Marking the role as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated }} + [ '{{ role_name }}' ]"
