---
- name: Creating the asset directory ...
  file:
    path: '{{ ansible_user_dir }}/.dev-sys/go'
    state: directory
    mode: u+rwx,go-rwx

- name: Getting or updating the package ...
  get_url:
    url: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
    dest: '{{ ansible_user_dir }}/.dev-sys/go/go{{ go_version }}.linux-amd64.tar.gz'
    mode: u+rw-x,go-rwx
  register: go_status

- name: Installing or updating ...
  when: go_status.changed == true
  block:

  - name: Removing the previous installation ...
    file:
      path: /usr/local/go
      state: absent
    become: yes

  - name: Installing ...
    unarchive:
      src: '{{ ansible_user_dir }}/.dev-sys/go/go{{ go_version }}.linux-amd64.tar.gz'
      dest: /usr/local
      remote_src: yes
    become: yes

  # End of block: name: Installing or updating ...

- name: Installing the Bash startup script ...
  copy:
    src: .bashrc.d/go-vars.sh
    dest: '{{ ansible_user_dir }}/.bashrc.d/go-vars.sh'
    mode: u+x

- name: Marking the role as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated }} + [ '{{ role_name }}' ]"
