---
- name: Installing ...
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    group: root
    mode: u+rwx,go+rx-w
    owner: root
  become: yes

- name: Creating the symbolic link for Docker Compose ...
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    group: root
    owner: root
    state: link
  become: yes

- name: Installing command completion ...
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose.version }}/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    group: root
    owner: root
  become: yes
