---
- name: Installing ...
  shell: >
    bash -c "source ~/.nvm/nvm.sh &&
    nvm install {{ nodejs_version }}"
  register: nvm_installation
  changed_when: "'is already installed.' not in nvm_installation.stderr"

- name: Checking the default version ...
  shell: >
    bash -c "source ~/.nvm/nvm.sh &&
    nvm ls --no-colors | grep -e 'default -> {{ nodejs_version }}'"
  register: nvm_check_for_correct_version
  changed_when: false
  failed_when: false

- name: Setting the default version ...
  shell: >
    bash -c "source ~/.nvm/nvm.sh &&
    nvm alias default {{ nodejs_version }}"
  when: nvm_check_for_correct_version.rc != 0

- name: Marking the role as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated }} + [ '{{ role_name }}' ]"
