---
- name: Installing ...
  shell: bash -c "source ~/.nvm/nvm.sh && nvm install {{ nodejs.version }}"
  register: nvm_install_status
  changed_when: "'is already installed.' not in nvm_install_status.stderr"

- name: Checking the default version ...
  shell: bash -c "source ~/.nvm/nvm.sh && nvm ls --no-colors | grep -e 'default -> {{ nodejs.version }}'"
  register: nvm_check_default
  changed_when: False
  failed_when: False

- name: Setting the default version ...
  shell: bash -c "source ~/.nvm/nvm.sh && nvm alias default {{ nodejs.version }}"
  when: nvm_check_default.rc != 0
