---
- when: (role_name ~ '-' ~ python_version) not in roles_evaluated
  import_tasks: tasks/evaluate.yml

- when: (role_name ~ '-' ~ python_version) not in roles_evaluated
  name: Marking {{ role_name ~ '-' ~ python_version }} as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated + [ (role_name ~ '-' ~ python_version) ] }}"
