---
- name: Installing ...
  apt:
    name: unzip
    force_apt_get: yes
    state: latest
  become: yes

- name: Marking the role as executed ...
  set_fact:
    roles_already_executed: "{{ roles_already_executed }} + [ '{{ role_name }}' ]"
