---
- name: Adding the apt key ...
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Adding the apt repository ...
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  become: yes

- name: Running apt update ...
  apt:
    update_cache: yes
  become: yes

- name: Installing ...
  apt:
    name: docker-ce
    state: latest
  become: yes

- name: Ensuring the service is started and enabled at boot ...
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Adding users to the Docker group ...
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  become: yes

- name: Installing Docker Compose ...
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    group: root
    mode: u+rwx,go+rx-w
    owner: root
  become: yes
