---
- hosts: dev_sys
  roles:
  - role: git
  - role: bash-environment
  - role: pyenv-environment
  - role: dev-sys
  # - role: aws-dev-venv
  # - role: aws-configuration
  #   when: aws_configuration.provision == true
  - role: ruby
  - role: linuxbrew
  - role: mkcert
  - role: nvm
  - role: nodejs
  - role: docker
  - role: docker-compose
  - role: sqlite
  - role: unzip
  - role: zip
