---
- hosts: dev_sys
  vars:
    roles_already_executed: []

  roles:
  - role: aws_cli
    tags: aws
    when: "'aws_cli' not in roles_already_executed"

  - role: bash_environment
    tags: always
    when: "'bash_environment' not in roles_already_executed"

  - role: dev_sys
    tags: always
    when: "'dev_sys' not in roles_already_executed"

  - role: docker
    tags: docker
    when: "'docker' not in roles_already_executed"

  - role: docker_compose
    tags: docker
    when: "'docker_compose' not in roles_already_executed"

  - role: git
    tags: git
    when: "'git' not in roles_already_executed"

  - role: go
    tags: go
    when: "'go' not in roles_already_executed"

  - role: mercurial
    tags: mercurial
    when: "'mercurial' not in roles_already_executed"

  - role: mkcert
    tags: mkcert
    when: "'mkcert' not in roles_already_executed"

  - role: nodejs
    tags: nodejs
    when: "'nodejs' not in roles_already_executed"

  - role: nvm
    tags: nvm
    when: "'nvm' not in roles_already_executed"

  - role: pyenv_environment
    tags: always
    when: "'pyenv_environment' not in roles_already_executed"

  - role: python
    tags: python
    when: "'python' not in roles_already_executed"

  - role: ruby
    tags: ruby
    when: "'ruby' not in roles_already_executed"

  - role: sqlite
    tags: sqlite
    when: "'sqlite' not in roles_already_executed"

  - role: unzip
    tags: zip
    when: "'zip' not in roles_already_executed"

  - role: update
    tags: update
    when: "'update' not in roles_already_executed"

  - role: upgrade
    tags: upgrade
    when: "'upgrade' not in roles_already_executed"

  - role: zip
    tags: zip
    when: "'zip' not in roles_already_executed"
