---
- hosts: dev_sys
  roles:
  - role: bash-environment
    tags: always

  - role: pyenv-environment
    tags: always

  - role: dev-sys
    tags: always

  - role: go
    tags: go

  - role: ruby
    tags: ruby

  - role: mkcert
    tags: mkcert

  - role: nvm
    tags: nvm

  - role: nodejs
    tags: nodejs

  - role: docker
    tags: docker

  - role: docker-compose
    tags: docker

  - role: sqlite
    tags: sqlite

  - role: unzip
    tags: zip

  - role: zip
    tags: zip
