---
- hosts: self
  vars:
    bash_environment:
      version: "feature/Issue-#11-Make-Bash-environment-more-Ansible-friendly"
    docker:
      users:
      - "{{ vagrant_user }}"
  roles:
  - role: update
  - role: upgrade
  - role: git
  - role: git-configuration
    when: git_configuration.provision == true
  - role: bash-environment
  - role: ansible-environment
  - role: git-environment
  - role: build-essential
  - role: python2
  - role: python3
  - role: virtualenv
  - role: aws-dev-venv
  - role: aws-configuration
    when: aws_configuration.provision == true
  - role: pipenv
  - role: ruby
  - role: linuxbrew
  - role: mkcert
  - role: nvm
  - role: nodejs
  - role: docker
  - role: docker-compose
  - role: sqlite
  - role: unzip
  - role: zip
