---
- name: Running apt-get update ...
  apt:
    force_apt_get: yes
    update_cache: yes
  become: yes

- name: Marking the role as evaluated ...
  set_fact:
    roles_evaluated: "{{ roles_evaluated }} + [ '{{ role_name }}' ]"
